version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t arrivals-service .
      - docker tag arrivals-service:latest $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/arrivals-service:latest
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/arrivals-service:latest
artifacts:
  files:
    - "**/*"
    
